---

- hosts: all
  vars:
    zsh_user: "{{ ansible_user }}"
    zsh_home: "{{ ansible_user_dir }}"
    i3_additional_packages:
       # Basics
      - btop
      - wget
      - curl
      - numlockx
      # Browsers
      - google-chrome
      - firefox
      - firefox-i18n-de
      - opera
      - chromium
      # Fonts
      - ttf-croscore
      - ttf-dejavu
      - ttf-droid
      - ttf-font-awesome
      - ttf-hack
      - ttf-hanazono
      - ttf-inconsolata
      - ttf-indic-otf
      - ttf-ms-fonts
      - ttf-roboto
      - ttf-sazanami
      - adobe-source-code-pro-fonts
      - adobe-source-han-sans-cn-fonts
      - adobe-source-han-sans-jp-fonts
      - adobe-source-han-sans-kr-fonts
      - adobe-source-han-sans-tw-fonts
      - awesome-terminal-fonts
      - cantarell-fonts
      - noto-fonts
      - noto-fonts-extra
      - noto-fonts-cjk
      - noto-fonts-emoji
      - powerline-fonts
      # File manager
      - nautilus
      - sushi
      - nautilus-sendto
      - nautilus-image-converter
      - seahorse-nautilus
      - gvfs-smb
      - gvfs-nfs
      - gvfs-mtp
      - gvfs-google
      - gvfs-afc
      # Media
      - mpv
      - vlc
      - totem
      - gstreamer
      - gstreamer-vaapi
      - gst-plugins-good
      - gst-plugins-base
      - ffmpeg
      - gst-libav
      # Communication
      - telegram-desktop
      - slack-desktop
      - skypeforlinux-stable-bin
  roles:
    - yay
    - network
    - wifi
    - bluetooth
    - ntp
    - yubikey
    - ssh
    - zsh
    - i3
    - audio
    - power
    - docker
    - phpdev
  pre_tasks:
    - name: "Update package cache"
      become: true
      changed_when: false
      pacman:
        update_cache: true
  tasks:
    - name: "Update dotfiles repository"
      git:
        repo: git@github.com:hikaru-shindo/dotfiles.git
        dest: "{{ ansible_user_dir }}/dotfiles"
        version: "main"
    - name: "Install dotfiles"
      shell: "{{ ansible_user_dir }}/dotfiles/install.sh"
      args:
        chdir: "{{ ansible_user_dir }}/dotfiles"
      changed_when: false
 
