---

- name: Setup Lenovo T480 specifics
  hosts: all
  tasks:
    - name: Install intel graphics drivers
      become: true
      package:
        name: xf86-video-intel
    - name: Install throttling fix
      become: true
      yay:
        name: lenovo-throttling-fix-git
    - name: Enable throttling fix service
      become: true
      shell: systemctl enable --now lenovo_fix.service
    - name: Ensure throttling fix started
      service:
        name: lenovo_fix
        state: started
    - name: Install intel microcode
      become: true
      package:
        name: intel-ucode
    - name: Update GRUB bootloader
      become: true
      shell: grub-mkconfig -o /boot/grub/grub.cfg
