---

- hosts: all
  vars:
    dockitems_to_remove:
      - Launchpad
      - Mail
      - Safari
      - Contacts
      - Notes
      - Reminders
      - Maps
      - Photos
      - iBooks
      - Podcasts
      - Home
      - Photos
      - TV
      - App Store
      - System Preferences
      - Calendar
    dockitems_to_persist:
      - name: Google Chrome
        path: "/Applications/Google Chrome.app"
        pos: 1
      - name: Firefox
        path: "/Applications/Firefox.app"
        pos: 2
      - name: Brave Browser
        path: /Applications/Brave Browser.app
        pos: 3
      - name: iTerm
        path: /Applications/iTerm.app
        pos: 4
      - name: Music
        path: /System/Applications/Music.app
        pos: 5
      - name: Telegram Desktop
        path: /Applications/Telegram Desktop.app
        pos: 6
  tasks:
    - name: Add warrensbox tap repo for tfswitch
      homebrew_tap:
        name: warrensbox/tap
        state: present
    - name: Install development helplers
      homebrew:
        state: present
        name:
          - jq
          - gnu-sed
          - git-secret
          - blackbox
          - pwgen
          - plantuml
          - xz
          - siege
          - diff-so-fancy
          - minikube
          - karn
    - name: Install misc stuff
      homebrew:
        state: present
        name:
          - neofetch
          - imagemagick
          - htop
          - wget
          - x265
          - lame
          - flac
          - yubico-piv-tool
          - ykman
          - ykpers
          - dockutil
          - minikube
          - kubectx
          - kube-ps1
          - tfswitch # warrensbox/tap
          - velero # kubernetes cluster backup
    - name: Install programming languages
      homebrew:
        state: present
        name:
          - go
          - python
          - yarn
          - elixir
          - erlang
          - openjdk
          - maven
          - gradle
    - name: Install kubernetes tooling
      homebrew:
        state: present
        name:
          - kubernetes-cli
          - helm
          - doctl
    - name: Install brew applications
      homebrew_cask:
        state: present
        accept_external_apps: yes # Ignore if alreay installed manually
        name:
          - sizeup
          - sequel-pro
          - maccy
          - iterm2
          - mobster
          - telegram-desktop
          - 1password
          - brave-browser
          - google-chrome
          - firefox
          - atom
          - docker
          - gpg-suite
          - jetbrains-toolbox
          - owasp-zap
          - obs
          - loopback
          - postman
          - google-japanese-ime
          - vlc
          - libreoffice
          - the-unarchiver
          - coconutbattery
          - app-cleaner
          - little-snitch
    - name: Setup maccy
      shell: defaults write org.p0deje.Maccy {{ item }}
      with_items:
        # see https://github.com/p0deje/Maccy/blob/master/README.md
        - historySize 30
        - hotKey command+shift+c
        - pasteByDefault true
    - name: Remove all crap from Dock
      shell: dockutil --remove '{{ item }}'
      ignore_errors: true
      with_items: "{{ dockitems_to_remove }}"
    - name: Check if items in dock exist
      shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}'
      with_items: "{{ dockitems_to_persist }}"
    - name: Fix order
      shell: dockutil --move '{{ item.name }}' --position {{ item.pos }}
      with_items: "{{ dockitems_to_persist }}"
    - name: "Update dotfiles repository"
      git:
        repo: git@github.com:hikaru-shindo/dotfiles.git
        dest: "{{ ansible_user_dir }}/dotfiles"
        version: "master"
    - name: "Install dotfiles"
      shell: "{{ ansible_user_dir }}/dotfiles/install.sh"
      args:
        chdir: "{{ ansible_user_dir }}/dotfiles"
      changed_when: false
