---

- hosts: all
  tasks:
    - name: Install development helplers
      homebrew:
        state: present
        name:
          - jq
          - git-secret
          - blackbox
          - pwgen
          - gnupg
          - plantuml
          - xz
          - siege
          - diff-so-fancy
    - name: Install misc stuff
      homebrew:
        state: present
        name:
          - neofetch
          - imagemagick
          - htop
          - wget
          - x265
          - lame
          - flac
          - yubico-piv-tool
          - ykman
          - ykpers
    - name: Install programming languages
      homebrew:
        state: present
        name:
          - go
          - python
          - yarn
          - elixir
          - erlang
          - openjdk
          - maven
          - gradle
    - name: Install kubernetes tooling
      homebrew:
        state: present
        name:
          - kubernetes-cli
          - helm
          - doctl
    - name: Install brew applications
      homebrew_cask:
        state: present
        accept_external_apps: yes # Ignore if alreay installed manually
        name: "{{ item }}"
      with_items:
        - sizeup
        - sequel-pro
        - maccy
        - iterm2
        - mobster
        - telegram-desktop
        - 1password
        - brave-browser
        - google-chrome
        - firefox
        - atom
        - docker
        - gpg-suite
        - jetbrains-toolbox
        - owasp-zap
        - obs
        - postman
        - google-japanese-ime
        - vlc
        - libreoffice
        - the-unarchiver
        - minikube
    - name: "Update dotfiles repository"
      git:
        repo: git@github.com:hikaru-shindo/dotfiles.git
        dest: "{{ ansible_user_dir }}/dotfiles"
        version: "master"
    - name: "Install dotfiles"
      shell: "{{ ansible_user_dir }}/dotfiles/install.sh"
      args:
        chdir: "{{ ansible_user_dir }}/dotfiles"
      changed_when: false
