---

- name: Basic setup
  hosts: all
  vars:
    zsh_user: "{{ ansible_user }}"
    zsh_home: "{{ ansible_user_dir }}"
    zsh_theme: "agnoster"
  roles:
    - yay
    - network
    - wifi
    - bluetooth
    - audio
    - ntp
    - yubikey
    - ssh
    - zsh
    - power
  pre_tasks:
    - name: "Update package cache"
      become: true
      changed_when: false
      pacman:
        update_cache: true
  tasks:
    - name: "Install basic packages"
      become: true
      pacman:
        name:
          - git
          - neovim
          - htop
          - ntp
          - wget
          - curl
          - numlockx
          - gpgme
    - name: Ensure global gitignore file
      copy:
        src: gitignore_global
        dest: "{{ ansible_user_dir }}/.gitignore_global"
    - name: Optimize makepkg build
      become: true
      lineinfile:
        dest: /etc/makepkg.conf
        line: "MAKEFLAGS=\"-j{{ ansible_processor_vcpus }}\""
        regexp: "^MAKEFLAGS="
    - name: Optimize makepkg compression
      become: true
      lineinfile:
        dest: /etc/makepkg.conf
        line: "COMPRESSXZ=(xz --threads={{ ansible_processor_vcpus }} -v -c -z -)"
        regexp: "^COMPRESSXZ="

- name: Install graphical interface
  hosts: all
  vars:
    browsers:
      - google-chrome
      - firefox
      - firefox-i18n-de
      - opera
      - chromium
  roles:
    - i3
  tasks:
    - name: Install fonts
      become: true
      yay:
        name:
          - ttf-croscore
          - ttf-dejavu
          - ttf-droid
          - ttf-font-awesome
          - ttf-hack
          - ttf-hanazono
          - ttf-inconsolata
          - ttf-indic-otf
          - ttf-ms-fonts
          - ttf-roboto
          - ttf-sazanami
          - adobe-source-code-pro-fonts
          - adobe-source-han-sans-cn-fonts
          - adobe-source-han-sans-jp-fonts
          - adobe-source-han-sans-kr-fonts
          - adobe-source-han-sans-tw-fonts
          - awesome-terminal-fonts
          - cantarell-fonts
          - noto-fonts
          - noto-fonts-extra
          - noto-fonts-cjk
          - noto-fonts-emoji
          - powerline-fonts
    - name: Install file manager
      become: true
      package:
        name:
          - nautilus
          - sushi
          - nautilus-sendto
          - nautilus-image-converter
          - seahorse-nautilus
          - nautilus-share
          - gvfs-smb
          - gvfs-nfs
          - gvfs-mtp
          - gvfs-google
          - gvfs-afc
    - name: Install web browsers
      become: true
      yay:
        name: "{{ browsers }}"

- name: Setup PHP development 
  hosts: all
  roles:
    - yay
    - docker
    - php
  tasks:
    - name: Install basic development dependencies
      become: true
      pacman:
        name:
          - make
    - name: Install PHP IDEs
      become: true
      yay:
        name:
          - phpstorm
          - visual-studio-code-bin
          - atom
    - name: Install development tools
      become: true
      yay:
        name: 
          - postman-bin

- name: Install communication tools
  hosts: all
  roles:
    - yay
  tasks:
    - name: Install telegram
      become: true
      package:
        name: telegram-desktop
    - name: Install Skype
      become: true
      yay:
        name: skypeforlinux-stable-bin
    - name: Install Slack
      become: true
      yay:
        name: slack-desktop
