---

- hosts: all
  roles:
    - yay
    - ntp
    - docker
  pre_tasks:
    - name: "Update package cache"
      become: true
      changed_when: false
      pacman:
        update_cache: true
  tasks:
    - name: "Install basic packages"
      become: true
      pacman:
        name:
          - git
          - gvim
          - htop
          - ntp
          - wget
          - curl
          - numlockx
    - name: Install IDEs
      become: true
      yay:
        name:
          - phpstorm
          - rubymine
          - goland
          - pycharm-professional
          - visual-studio-code-bin
          - android-studio
    - name: Install browsers
      become: true
      yay:
        name:
          - google-chrome
          - chromium
          - firefox
          - firefox-i18n-de
          - opera
