---

- hosts: all
  roles:
    - pacaur
    - ntp
  pre_tasks:
    - name: "Update package cache"
      become: true
      changed_when: false
      pacman:
        update_cache: true
  tasks:
    - name: "Install basic packages"
      become: true
      pacman:
        name: "{{ item }}"
      with_items:
        - git
        - gvim
        - htop
        - ntp
        - wget
        - curl
        - numlockx
    - name: Install IDEs
      become: true
      pacaur:
        name: "{{ item }}"
      with_items:
        - phpstorm
        - rubymine
        - goland
        - pycharm-professional
        - visual-studio-code-bin
        - android-studio
    - name: Install browsers
      become: true
      pacaur:
        name: "{{ item }}"
      with_items:
        - google-chrome
        - firefox
        - firefox-i18n-de
        - opera
