---

- name: Install ACPI tooling
  become: true
  package:
    name: acpi
    state: present

- name: Install power manager
  become: true
  package:
    name: xfce4-power-manager
    state: present
