---

- name: Install bluez
  become: true
  package:
    name:
      - bluez
      - bluez-utils
    state: present
  notify: restart bluetooth

- name: Enable bluetooth service
  become: true
  service:
    name: bluetooth
    enabled: yes
    state: started

- name: "Add current user to lp group"
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: lp
    append: true

- name: Install bluetooth control tools
  become: true
  package:
    name:
      - blueman
      - blueberry 
