---

- name: Ensure bluez installed
  become: true
  package:
    state: present
    name:
      - bluez
      - bluez-utils
  notify: restart bluetooth

- name:  Ensure bluetooth service enabled and started
  become: true
  service:
    name: bluetooth
    state: started
    enabled: yes

- name: Add current user to lp group"
  become: true
  user:
    name: "{{ item }}"
    groups: lp
    append: true
  loop: "{{ bluetooth_users }}"

- name: Ensure bluetooth UIs installed
  become: true
  package:
    state: present
    name:
      - blueman
      - blueberry
