---

- name: Install xorg-xserver
  become: true
  package:
    name: 
      - xorg-server
      - xorg-xinit
    state: present

- name: Install additional xorg packages
  become: true
  package:
    name:
      - xorg-setxkbmap
      - xorg-xrandr
      - xorg-xbacklight
    state: present

- name: Install i3wm
  become: true
  package:
    name:
      - i3-gaps
      - i3blocks
      - i3lock
      - i3status
    state: present

- name: Install additional tools
  become: true
  package:
    name:
      - dmenu
      - nitrogen
    state: present

- name: Ensure dbus
  become: true
  package:
    name: dbus
    state: present

- name: Install lockers
  become: true
  yay:
    name:
      - slock
      - i3lock-fancy-multimonitor-git
    state: present

- name: Ensure .xinitrc exists
  file:
    path: "{{ ansible_user_dir }}/.xinitrc"
    state: touch
  changed_when: false

- name: Start i3wm on starting xorg-server
  lineinfile:
    line: exec dbus-launch i3
    dest: "{{ ansible_user_dir }}/.xinitrc"
    regexp: "^exec dbus-launch i3$"

- name: Ensure profile file exists
  file:
    path: "{{ ansible_user_dir }}/{{ i3_profile_file }}"
    state: touch
  changed_when: false

- name: Start xort-server on login
  lineinfile:
    line: "if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then exec startx; exit; fi"
    dest: "{{ ansible_user_dir }}/{{ i3_profile_file }}"
    regexp: exec startx

- name: Ensures i3 config dir exists
  file:
    path: "{{ ansible_user_dir }}/.config/i3" 
    state: directory

- name: Configure i3
  copy:
    src: "{{ i3_config_file }}"
    dest: "{{ ansible_user_dir }}/.config/i3/config"

- name: Install Arc themes
  become: true
  yay:
    name:
      - arc-gtk-theme
      - arc-solid-gtk-theme
      - arc-icon-theme
    state: present

- name: Setup GTK2
  copy:
    src: gtk2.config
    dest: "{{ ansible_user_dir }}/.gtkrc-2.0"

- name: Ensure GTK3 config dir exists
  file:
    path: "{{ ansible_user_dir }}/.config/gtk-3.0"
    state: directory

- name: Setup GTK3
  copy:
    src: gtk3.config
    dest: "{{ ansible_user_dir }}/.config/gtk-3.0/settings.ini"

- name: Install additional packages
  become: true
  yay:
    name: "{{ i3_additional_packages }}"
    state: present
